(function () {
  const statusEl = document.getElementById('status');
  const container = document.getElementById('tablesContainer');
  const refreshBtn = document.getElementById('refreshBtn');

  function setStatus(msg, isError = false) {
    statusEl.textContent = msg;
    statusEl.style.color = isError ? '#fca5a5' : '#9ca3af';
  }

  async function loadTables() {
    try {
      setStatus('Loading tables...');
      const { tables } = await API.getTables();
      container.innerHTML = '';
      if (!tables || Object.keys(tables).length === 0) {
        setStatus('No tables available. Go back and collect data.', true);
        return;
      }
      setStatus('');
      Object.entries(tables).forEach(([name, html]) => {
        const block = document.createElement('section');
        block.className = 'table-block';
        const title = document.createElement('h2');
        title.textContent = name;
        const content = document.createElement('div');
        content.innerHTML = html; // HTML generated by pandas
        block.appendChild(title);
        block.appendChild(content);
        container.appendChild(block);
      });
    } catch (err) {
      setStatus(err.message || 'Failed to load tables.', true);
    }
  }

  refreshBtn.addEventListener('click', loadTables);
  window.addEventListener('DOMContentLoaded', loadTables);
})();
